apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: runner-manager
  namespace: agent-runner
spec:
  ingressClassName: nginx
  rules:
    - host: chores.nala.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: runner-manager
                port:
                  name: http
